Repository Battle-s/battle-school-backend, pull requests merged in 2022-08, with the labels that each got.

#10 [feature] #8 h2 문제 해결
  src/main/java/org/battles/battles/security/SecurityConfig.java
  src/main/resources/application.properties
Labels: bugfix :hand:, backend :desktop_computer:

#12 [feature] #11 Swagger 설정
  build.gradle
  src/main/java/org/battles/battles/security/SwaggerConfig.java
Labels: backend :desktop_computer:

#13 Feature/#7 user생성
  src/main/java/org/battles/battles/BattlesApplication.java
  src/main/java/org/battles/battles/common/TimeStamped.java
  src/main/java/org/battles/battles/security/SecurityConfig.java
  src/main/java/org/battles/battles/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/battles/battles/security/jwt/JwtTokenProvider.java
  src/main/java/org/battles/battles/user/Role.java
  src/main/java/org/battles/battles/user/User.java
  src/main/java/org/battles/battles/user/UserController.java
  src/main/java/org/battles/battles/user/UserRepository.java
  src/main/java/org/battles/battles/user/UserService.java
  src/main/java/org/battles/battles/user/UserStatus.java
Labels: feature :computer:, backend :desktop_computer:

#16 [feature] #15 학교 Entity 생성
  src/main/java/org/battles/battles/school/School.java
  src/main/java/org/battles/battles/school/SchoolRepository.java
Labels: feature :computer:, backend :desktop_computer:

#18 Feature/#14 예외advice세팅
  src/main/java/org/battles/battles/common/TimeStamped.java
  src/main/java/org/battles/battles/exception/ExceptionAdvice.java
  src/main/java/org/battles/battles/exception/exception/CAccessDeniedException.java
  src/main/java/org/battles/battles/exception/exception/CAuthenticationEntryPointException.java
  src/main/java/org/battles/battles/exception/exception/CTokenUserNotFoundException.java
  src/main/java/org/battles/battles/exception/exception/CUserNotFoundException.java
  src/main/java/org/battles/battles/response/CommonResult.java
  src/main/java/org/battles/battles/response/ListResult.java
  src/main/java/org/battles/battles/response/SingleResult.java
  src/main/java/org/battles/battles/security/SwaggerConfig.java
  src/main/java/org/battles/battles/security/jwt/ExceptionController.java
  src/main/java/org/battles/battles/security/jwt/JwtTokenProvider.java
  src/main/java/org/battles/battles/user/UserService.java
Labels: backend :desktop_computer:

#22 Feature/#21 git협업세팅
  .github/pull_request_template.md
  .github/workflows/gradle.yml
Labels: setting :hammer:, backend :desktop_computer:

#23 [feature] #19 bean dependency cycle 해결 및 토큰 유효 검사 코드 추가
  src/main/java/org/battles/battles/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/battles/battles/security/jwt/JwtTokenProvider.java
  src/main/java/org/battles/battles/user/UserService.java
Labels: backend :desktop_computer:

#25 Feature/#24 jpa설정추가
  .gitignore
  src/main/resources/application.properties
Labels: backend :desktop_computer:

#28 [feature] #26 Entity 생성
  .gitignore
  src/main/java/org/battles/battles/comment/Comment.java
  src/main/java/org/battles/battles/post/Post.java
  src/main/java/org/battles/battles/post/PostType.java
Labels: review :pray:, feature :computer:, backend :desktop_computer:

#34 Feature/#32 학교엔티티 사용자 매핑을 위한 가입 로직에 코드 추가
  src/main/java/org/battles/battles/common/ValidStringUtils.java
  src/main/java/org/battles/battles/exception/ExceptionAdvice.java
  src/main/java/org/battles/battles/exception/exception/CEmailExistedException.java
  src/main/java/org/battles/battles/exception/exception/CNicknameExistedException.java
  src/main/java/org/battles/battles/exception/exception/CNotSchoolEmailException.java
  src/main/java/org/battles/battles/exception/exception/CNotValidEmailException.java
  src/main/java/org/battles/battles/exception/exception/CSchoolNameSchoolDomainException.java
  src/main/java/org/battles/battles/response/CommonResultType.java
  src/main/java/org/battles/battles/response/ListResult.java
  src/main/java/org/battles/battles/response/ResponseService.java
  src/main/java/org/battles/battles/school/SchoolRepository.java
  src/main/java/org/battles/battles/school/SchoolService.java
  src/main/java/org/battles/battles/security/CorConfig.java
  src/main/java/org/battles/battles/security/SecurityConfig.java
  src/main/java/org/battles/battles/user/Dto/SignUpDto.java
  src/main/java/org/battles/battles/user/Token.java
  src/main/java/org/battles/battles/user/User.java
  src/main/java/org/battles/battles/user/UserController.java
  src/main/java/org/battles/battles/user/UserRepository.java
  src/main/java/org/battles/battles/user/UserService.java
Labels: review :pray:, feature :computer:, backend :desktop_computer:

#37 Feature/#26 게시판기능구현
  src/main/java/org/battles/battles/comment/Comment.java
  src/main/java/org/battles/battles/comment/CommentController.java
  src/main/java/org/battles/battles/comment/CommentRepository.java
  src/main/java/org/battles/battles/comment/CommentService.java
  src/main/java/org/battles/battles/common/Status.java
  src/main/java/org/battles/battles/post/Post.java
  src/main/java/org/battles/battles/post/PostController.java
  src/main/java/org/battles/battles/post/PostRepository.java
  src/main/java/org/battles/battles/post/PostService.java
  src/main/java/org/battles/battles/user/AuthService.java
  src/main/java/org/battles/battles/user/User.java
  src/main/java/org/battles/battles/user/UserStatus.java
Labels: bugfix :hand:, backend :desktop_computer:

#39 [feature] #36 회원 탈퇴 기능 추가
  src/main/java/org/battles/battles/user/User.java
  src/main/java/org/battles/battles/user/UserController.java
  src/main/java/org/battles/battles/user/UserService.java
Labels: done :heavy_check_mark:, review :pray:, feature :computer:, backend :desktop_computer:

#41 [feature] #40 모든 학교 조회 기능 추가
  src/main/java/org/battles/battles/school/SchoolController.java
  src/main/java/org/battles/battles/school/SchoolService.java
Labels: done :heavy_check_mark:, review :pray:, feature :computer:, backend :desktop_computer:

#45 [feature] #17 rds 연동
  .gitignore
  build.gradle
  src/main/resources/application.properties
Labels: setting :hammer:, done :heavy_check_mark:, feature :computer:, backend :desktop_computer:

#46 Feature/#42 종목엔티티
  src/main/java/org/battles/battles/battle/category/Category.java
  src/main/java/org/battles/battles/battle/category/CategoryArea.java
  src/main/java/org/battles/battles/battle/category/CategoryController.java
  src/main/java/org/battles/battles/battle/category/CategoryRepository.java
  src/main/java/org/battles/battles/battle/category/CategoryRequestDto.java
  src/main/java/org/battles/battles/battle/category/CategoryResponseDto.java
  src/main/java/org/battles/battles/battle/category/CategoryService.java
  src/main/java/org/battles/battles/common/Status.java
  src/main/java/org/battles/battles/common/TimeStamped.java
  src/main/java/org/battles/battles/exception/ExceptionAdvice.java
  src/main/java/org/battles/battles/exception/exception/CCategoryExistedException.java
  src/main/java/org/battles/battles/exception/exception/CCategoryNotFoundException.java
Labels: review :pray:, feature :computer:, backend :desktop_computer:

#48 Feature/#44 경기생성
  src/main/java/org/battles/battles/battle/Battle.java
  src/main/java/org/battles/battles/battle/BattleController.java
  src/main/java/org/battles/battles/battle/BattleRepository.java
  src/main/java/org/battles/battles/battle/BattleRequestDto.java
  src/main/java/org/battles/battles/battle/BattleResponseDto.java
  src/main/java/org/battles/battles/battle/BattleService.java
  src/main/java/org/battles/battles/battle/category/CategoryController.java
  src/main/java/org/battles/battles/battle/category/CategoryRepository.java
  src/main/java/org/battles/battles/battle/category/CategoryService.java
  src/main/java/org/battles/battles/battle/season/SeasonController.java
  src/main/java/org/battles/battles/battle/season/SeasonService.java
  src/main/java/org/battles/battles/exception/ExceptionAdvice.java
  src/main/java/org/battles/battles/exception/exception/CBattleExistedException.java
  src/main/java/org/battles/battles/exception/exception/CBattleNotFoundException.java
  src/main/java/org/battles/battles/exception/exception/CCategoryInactiveException.java
  src/main/java/org/battles/battles/exception/exception/CSeasonInactiveException.java
Labels: feature :computer:, backend :desktop_computer:
